@extends('layouts.app')
@section('title', 'Clinic Inventory')
@section('content')
<div class="mx-auto max-w-6xl space-y-5"><div class="flex flex-col gap-4 rounded-2xl bg-white p-5 shadow sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-wide text-blue-700">School Clinic</p><h1 class="mt-1 text-2xl font-black">Clinic Inventory</h1></div><a href="{{ route('clinic.dashboard') }}" class="rounded-xl bg-gray-100 px-4 py-3 text-center text-sm font-bold">← Back to Dashboard</a></div>
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
<form method="POST" action="{{ route('clinic.inventory.store') }}" class="grid gap-3 rounded-2xl bg-white p-5 shadow sm:grid-cols-2 lg:grid-cols-5">@csrf<input name="name" required placeholder="Item" class="rounded-xl border px-3 py-3"><input name="category" placeholder="Category" class="rounded-xl border px-3 py-3"><input name="quantity" type="number" step="0.01" min="0" required placeholder="Quantity" class="rounded-xl border px-3 py-3"><input name="minimum_quantity" type="number" step="0.01" min="0" required placeholder="Minimum" class="rounded-xl border px-3 py-3"><div class="flex gap-2"><input name="unit" value="units" required class="min-w-0 flex-1 rounded-xl border px-3 py-3"><button class="rounded-xl bg-blue-700 px-4 py-3 font-bold text-white">Add</button></div></form>
<div id="supply-request" class="rounded-2xl bg-white p-5 shadow"><h2 class="text-xl font-black text-gray-900">Request Supplies</h2><form method="POST" action="{{ route('clinic.supply-requests.store') }}" class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@csrf<input name="item_name" required placeholder="Item needed" class="rounded-xl border px-3 py-3"><input name="quantity_requested" type="number" step="0.01" min="0.01" required placeholder="Quantity" class="rounded-xl border px-3 py-3"><input name="unit" value="units" required placeholder="Unit" class="rounded-xl border px-3 py-3"><div class="flex gap-2"><input name="reason" placeholder="Reason" class="min-w-0 flex-1 rounded-xl border px-3 py-3"><button class="rounded-xl bg-amber-500 px-4 py-3 font-black text-slate-900">Request</button></div></form></div>
<div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($items as $item)<div class="rounded-2xl {{ $item->isLowStock() ? 'border-2 border-rose-300 bg-rose-50' : 'bg-white' }} p-5 shadow"><div class="flex items-start justify-between gap-3"><div><h2 class="font-black text-gray-900">{{ $item->name }}</h2><p class="text-xs text-gray-500">{{ $item->category ?: 'General' }}</p></div>@if($item->isLowStock())<span class="rounded-full bg-rose-200 px-2 py-1 text-[10px] font-black text-rose-800">LOW STOCK</span>@endif</div><p class="mt-4 text-3xl font-black text-blue-800">{{ $item->quantity }} <span class="text-sm font-bold text-gray-500">{{ $item->unit }}</span></p><p class="mt-1 text-xs text-gray-500">Minimum: {{ $item->minimum_quantity }} {{ $item->unit }}</p><form method="POST" action="{{ route('clinic.inventory.transactions.store', $item) }}" class="mt-4 grid gap-2 sm:grid-cols-3">@csrf<select name="type" class="rounded-lg border px-2 py-2 text-xs"><option value="received">Received</option><option value="used">Used</option><option value="adjusted">Adjusted</option></select><input name="quantity" type="number" min="0.01" step="0.01" required placeholder="Qty" class="rounded-lg border px-2 py-2 text-xs"><button class="rounded-lg bg-blue-700 px-2 py-2 text-xs font-bold text-white">Update</button></form></div>@empty<p class="rounded-2xl bg-white p-8 text-center text-sm text-gray-500 sm:col-span-2 lg:col-span-3">No inventory items yet.</p>@endforelse</div>
<div class="rounded-2xl bg-white p-5 shadow"><h2 class="text-xl font-black text-gray-900">Supply Requests</h2><div class="mt-4 space-y-3">@forelse($requests as $request)<div class="rounded-xl border border-gray-100 bg-gray-50 p-4"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p class="font-bold text-gray-900">{{ $request->item_name }} · {{ $request->quantity_requested }} {{ $request->unit }}</p><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">{{ ucfirst($request->status) }}</span></div><p class="mt-1 text-xs text-gray-500">Requested by {{ $request->requester->name }}{{ $request->reason ? ' · ' . $request->reason : '' }}</p>@if(auth()->user()->isAdmin() && $request->status === 'pending')<form method="POST" action="{{ route('clinic.supply-requests.review', $request) }}" class="mt-3 flex flex-wrap gap-2">@csrf @method('PUT')<select name="status" class="rounded-lg border px-2 py-2 text-xs"><option value="approved">Approve</option><option value="rejected">Reject</option><option value="fulfilled">Fulfilled</option></select><input name="review_notes" placeholder="Admin note" class="min-w-0 flex-1 rounded-lg border px-2 py-2 text-xs"><button class="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Save</button></form>@endif</div>@empty<p class="text-sm text-gray-500">No supply requests yet.</p>@endforelse</div></div></div>
@endsection
