@extends('layouts.app')
@section('title', 'New Incident')
@section('content')
<div class="mx-auto max-w-4xl space-y-5"><div class="rounded-2xl bg-gradient-to-r from-blue-700 to-cyan-700 p-6 text-white shadow"><h1 class="text-2xl font-black">New Incident Report</h1><p class="mt-1 text-sm text-blue-100">Record sports, playground, classroom, or other school incidents.</p></div>
@if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('clinic.incidents.store') }}" class="space-y-5 rounded-2xl bg-white p-5 shadow sm:p-8">@csrf
<div><label class="mb-1 block text-sm font-bold">Student</label><input name="student_id" type="number" value="{{ $student?->id ?: old('student_id') }}" required class="w-full rounded-xl border px-4 py-3"><p class="mt-1 text-xs text-gray-500">Open this form from a student profile to preselect the student.</p></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1 block text-sm font-bold">Incident date/time</label><input type="datetime-local" name="incident_at" value="{{ old('incident_at', now()->format('Y-m-d\TH:i')) }}" required class="w-full rounded-xl border px-4 py-3"></div><div><label class="mb-1 block text-sm font-bold">Incident type</label><select name="incident_type" required class="w-full rounded-xl border px-4 py-3"><option>Sports injury</option><option>Playground accident</option><option>Classroom injury</option><option>Other</option></select></div></div>
<div><label class="mb-1 block text-sm font-bold">Location</label><input name="location" class="w-full rounded-xl border px-4 py-3"></div><div><label class="mb-1 block text-sm font-bold">Description</label><textarea name="description" required rows="4" class="w-full rounded-xl border px-4 py-3"></textarea></div><div><label class="mb-1 block text-sm font-bold">Injury details</label><textarea name="injury_details" rows="3" class="w-full rounded-xl border px-4 py-3"></textarea></div><div><label class="mb-1 block text-sm font-bold">Action taken</label><textarea name="action_taken" rows="3" class="w-full rounded-xl border px-4 py-3"></textarea></div><div><label class="mb-1 block text-sm font-bold">Referred to</label><input name="referred_to" class="w-full rounded-xl border px-4 py-3"></div><label class="flex items-center gap-3 rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-900"><input type="checkbox" name="parent_contacted" value="1"> Parent / guardian contacted</label><input type="datetime-local" name="parent_contacted_at" class="w-full rounded-xl border px-4 py-3">
<div class="flex flex-col gap-3 sm:flex-row sm:justify-end"><a href="{{ route('clinic.dashboard') }}" class="rounded-xl bg-gray-100 px-5 py-3 text-center font-bold">← Back to Dashboard</a><button class="rounded-xl bg-blue-700 px-5 py-3 font-black text-white">Save Incident</button></div></form></div>
@endsection
