<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; color: #333; }
        .header { background: #059669; color: white; padding: 20px; text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 24px; }
        .header p { margin: 5px 0; }
        .info-box { background: #f3f4f6; padding: 15px; margin-bottom: 20px; border-left: 4px solid #059669; }
        .info-box p { margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #059669; color: white; padding: 12px; text-align: left; font-weight: bold; }
        td { padding: 10px 12px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f9fafb; }
        .pass { color: #059669; font-weight: bold; }
        .fail { color: #dc2626; font-weight: bold; }
        .footer { text-align: center; color: #666; font-size: 12px; margin-top: 30px; }
    </style>
</head>
<body>
    <div class="header">
        <h1><?php echo e(config('app.name', 'CBT System')); ?></h1>
        <p><strong>Class Results Report</strong></p>
    </div>

    <div class="info-box">
        <p><strong>Class:</strong> <?php echo e($class->name); ?></p>
        <p><strong>Description:</strong> <?php echo e($class->description); ?></p>
        <p><strong>Form Teacher:</strong> <?php echo e($formTeacher->teacher->name); ?></p>
        <p><strong>Report Generated:</strong> <?php echo e($generatedDate); ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Roll Number</th>
                <th>Total Score</th>
                <th>Total Marks</th>
                <th>Average %</th>
                <th>Exams Taken</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $resultSummary; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index => $result): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($index + 1); ?></td>
                <td><strong><?php echo e($result['name']); ?></strong></td>
                <td><?php echo e($result['rollNumber']); ?></td>
                <td><?php echo e($result['totalScore']); ?></td>
                <td><?php echo e($result['totalMarks']); ?></td>
                <td>
                    <span class="<?php echo e($result['average'] >= 50 ? 'pass' : 'fail'); ?>">
                        <?php echo e($result['average']); ?>%
                    </span>
                </td>
                <td><?php echo e($result['attempts']); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official document generated by <?php echo e(config('app.name')); ?></p>
        <p>© <?php echo e(date('Y')); ?> All Rights Reserved</p>
    </div>
</body>
</html>
<?php /**PATH C:\laragon\www\modern-cbt-platform-for-highschool\resources\views\teacher\class-results-pdf.blade.php ENDPATH**/ ?>