@extends('layouts.app')

@section('title', 'Classroom Oversight')

@section('content')
<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-4 rounded-2xl bg-gradient-to-r from-violet-700 to-indigo-700 p-6 text-white shadow-xl sm:flex-row sm:items-center sm:justify-between sm:p-8">
        <div><p class="text-xs font-bold uppercase tracking-[0.18em] text-violet-100">Administrator view</p><h1 class="mt-2 text-3xl font-black">Classroom Oversight</h1><p class="mt-2 text-violet-100">Monitor activities, learner completion, and teacher marking across every class.</p></div>
        <a href="{{ route('admin.classroom-activities') }}" class="rounded-xl bg-white px-5 py-3 text-center text-sm font-black text-violet-800 shadow hover:bg-violet-50">Open activities</a>
    </div>

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Activities created', $summary['activities'], 'bg-violet-50 text-violet-800'], ['Learner submissions', $summary['completed'], 'bg-emerald-50 text-emerald-800'], ['Still to submit', max(0, $summary['assigned'] - $summary['completed']), 'bg-amber-50 text-amber-800'], ['Awaiting marking', $summary['awaiting_review'], 'bg-rose-50 text-rose-800']] as [$label, $value, $colour])
            <div class="rounded-2xl p-5 shadow-sm {{ $colour }}"><p class="text-sm font-bold">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></div>
        @endforeach
    </div>

    <div class="grid gap-6 xl:grid-cols-2">
        <section class="overflow-hidden rounded-2xl bg-white shadow"><div class="border-b border-gray-100 p-5"><h2 class="text-xl font-black text-gray-900">Questions set today</h2><p class="mt-1 text-sm text-gray-500">The number of questions added today for each class.</p></div><div class="divide-y divide-gray-100">@forelse($todayQuestionByClass->sortBy('class_name') as $class)<div class="flex items-center justify-between px-5 py-4"><span class="font-bold text-gray-900">{{ $class['class_name'] }}</span><span class="rounded-full bg-indigo-100 px-3 py-1 text-sm font-black text-indigo-800">{{ $class['questions'] }} question{{ $class['questions'] === 1 ? '' : 's' }}</span></div>@empty<div class="p-8 text-center text-sm text-gray-500">No questions have been set today.</div>@endforelse</div></section>
        <section class="overflow-hidden rounded-2xl bg-white shadow"><div class="border-b border-gray-100 p-5"><h2 class="text-xl font-black text-gray-900">Teacher marking status</h2><p class="mt-1 text-sm text-gray-500">Submitted work that has not been published still needs marking or review.</p></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-950 text-xs uppercase text-white"><tr><th class="px-4 py-3">Teacher</th><th class="px-4 py-3 text-center">Activities</th><th class="px-4 py-3 text-center">Marked</th><th class="px-4 py-3 text-center">To mark</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($teacherReview as $teacher)<tr><td class="px-4 py-4 font-bold text-gray-900">{{ $teacher->name }}</td><td class="px-4 py-4 text-center">{{ $teacher->activities }}</td><td class="px-4 py-4 text-center font-bold text-emerald-700">{{ $teacher->marked }}</td><td class="px-4 py-4 text-center font-bold {{ $teacher->awaiting_review ? 'text-rose-700' : 'text-gray-500' }}">{{ $teacher->awaiting_review }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-gray-500">No classroom activities yet.</td></tr>@endforelse</tbody></table></div></section>
    </div>

    <section class="overflow-hidden rounded-2xl bg-white shadow"><div class="border-b border-gray-100 p-5"><h2 class="text-xl font-black text-gray-900">All classwork, assignments, quizzes, and tests</h2><p class="mt-1 text-sm text-gray-500">Completion is counted once per learner for each activity.</p></div><div class="overflow-x-auto"><table class="min-w-[1000px] w-full text-left text-sm"><thead class="bg-slate-950 text-xs uppercase text-white"><tr><th class="px-4 py-3">Activity</th><th class="px-4 py-3">Class / subject</th><th class="px-4 py-3">Teacher</th><th class="px-4 py-3 text-center">Questions</th><th class="px-4 py-3 text-center">Done</th><th class="px-4 py-3 text-center">Not done</th><th class="px-4 py-3 text-center">Marked</th><th class="px-4 py-3 text-center">To mark</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($activityRows as $row)<tr><td class="px-4 py-4"><span class="rounded-full bg-cyan-100 px-2 py-1 text-xs font-bold uppercase text-cyan-800">{{ $row->session->assessment_type }}</span><p class="mt-2 font-black text-gray-900">{{ $row->session->title }}</p><p class="mt-1 text-xs text-gray-500">{{ $row->session->is_published ? 'Published to learners' : 'Draft' }} · {{ $row->session->created_at->format('j M Y') }}</p></td><td class="px-4 py-4"><p class="font-bold text-gray-900">{{ $row->class_names }}</p><p class="mt-1 text-xs text-gray-500">{{ $row->session->subject?->name ?? 'No subject' }}</p></td><td class="px-4 py-4 text-gray-700">{{ $row->session->creator?->name ?? 'Unknown' }}</td><td class="px-4 py-4 text-center font-bold">{{ $row->session->questions_count }}</td><td class="px-4 py-4 text-center font-bold text-emerald-700">{{ $row->completed }}/{{ $row->assigned }}</td><td class="px-4 py-4 text-center font-bold {{ $row->assigned > $row->completed ? 'text-amber-700' : 'text-gray-500' }}">{{ max(0, $row->assigned - $row->completed) }}</td><td class="px-4 py-4 text-center font-bold text-emerald-700">{{ $row->marked }}</td><td class="px-4 py-4 text-center font-bold {{ $row->awaiting_review ? 'text-rose-700' : 'text-gray-500' }}">{{ $row->awaiting_review }}</td><td class="px-4 py-4"><a href="{{ route('admin.learning-sessions.submissions', $row->session) }}" class="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white hover:bg-indigo-700">View learners</a></td></tr>@empty<tr><td colspan="9" class="px-4 py-10 text-center text-gray-500">No classroom activities have been created yet.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
